# AdonisJS Sample Application

version: "3.8"

volumes:
  exclude:
  pgdata:

services:

  api:
    image: banana-stand-api
    build:
      context: ./api
    ports:
      - "3333:3333"
      - "5173:5173"
    # env_file:
    #   - ./api/.env
    depends_on:
      - db
    volumes:
      - ./api:/home/node/app/
      - exclude:/home/node/app/node_modules/
    stdin_open: true
    tty: true
    
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: banana
      POSTGRES_PASSWORD: stand
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./support/postgres/init_databases.sh:/docker-entrypoint-initdb.d/initializer.sh
